version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "ls && dotnet restore ./MvcTest.sln && dotnet publish ./MvcTest.sln -c Release -o ./obj/Docker/publish && ls"
